//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymkhanaLibrary {
    
    public partial class AdminLiveDashboard {
        protected global::System.Web.UI.WebControls.Content cHead;
        protected global::System.Web.UI.WebControls.Content cBody;
        protected global::System.Web.UI.WebControls.Literal litServerTime;
        protected global::System.Web.UI.WebControls.Literal litTotalBooks;
        protected global::System.Web.UI.WebControls.Literal litTotalTitles;
        protected global::System.Web.UI.WebControls.Literal litAvailableBooks;
        protected global::System.Web.UI.WebControls.Literal litIssuedBooks;
        protected global::System.Web.UI.WebControls.Literal litReturnedToday;
        protected global::System.Web.UI.WebControls.Literal litDueToday;
        protected global::System.Web.UI.WebControls.Literal litOverdueBooks;
        protected global::System.Web.UI.WebControls.Literal litReservedBooks;
        protected global::System.Web.UI.WebControls.Literal litActiveMembers;
        protected global::System.Web.UI.WebControls.Literal litLostBooks;
        protected global::System.Web.UI.WebControls.Literal litFineCollection;
        protected global::System.Web.UI.WebControls.GridView gvRecentActivity;
        protected global::System.Web.UI.WebControls.GridView gvMostBorrowed;
        protected global::System.Web.UI.WebControls.Panel pnlCover;
        protected global::System.Web.UI.WebControls.Repeater rptRecentBooks;
        protected global::System.Web.UI.WebControls.GridView gvActiveMembers;
        protected global::System.Web.UI.WebControls.Repeater rptAlerts;
        protected global::System.Web.UI.WebControls.Repeater rptInventoryStatus;
        protected global::System.Web.UI.WebControls.Literal litActivePOs;
        protected global::System.Web.UI.WebControls.Literal litReceivedBooks;
        protected global::System.Web.UI.WebControls.Literal litPendingApproval;
        protected global::System.Web.UI.WebControls.Literal litTodayFine;
        protected global::System.Web.UI.WebControls.Literal litMonthlyFine;
        protected global::System.Web.UI.WebControls.Literal litOutstandingFine;
        protected global::System.Web.UI.WebControls.Literal litCollectedYear;
        protected global::System.Web.UI.WebControls.Calendar calLibraryEvents;
    }
}
