//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymkhanaLibrary {
    
    public partial class AttendanceHistory {
        protected global::System.Web.UI.WebControls.Content cHead;
        protected global::System.Web.UI.WebControls.Content cBody;
        protected global::System.Web.UI.WebControls.Button btnBackToEntry;
        protected global::System.Web.UI.WebControls.Panel pnlAlertMessage;
        protected global::System.Web.UI.WebControls.Label lblAlertText;
        protected global::System.Web.UI.WebControls.TextBox txtFilterFromDate;
        protected global::System.Web.UI.WebControls.TextBox txtFilterToDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterMemberType;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;
        protected global::System.Web.UI.WebControls.TextBox txtFilterName;
        protected global::System.Web.UI.WebControls.TextBox txtFilterMemberNo;
        protected global::System.Web.UI.WebControls.Button btnFilterReset;
        protected global::System.Web.UI.WebControls.Button btnFilterSearch;
        protected global::System.Web.UI.WebControls.GridView gvAttendanceHistory;
        protected global::System.Web.UI.WebControls.Button btnTodayReport;
        protected global::System.Web.UI.WebControls.Button btnMonthlyReport;
        protected global::System.Web.UI.WebControls.Button btnSummaryReport;
        protected global::System.Web.UI.WebControls.Button btnPrint;
        protected global::System.Web.UI.WebControls.Button btnExportExcel;
        protected global::System.Web.UI.WebControls.Button btnExportPDF;
    }
}
