//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Pages_Books_BookList {
    protected global::System.Web.UI.WebControls.Content cHead;
    protected global::System.Web.UI.WebControls.Content cBody;
    protected global::System.Web.UI.WebControls.Panel pnlSuccess;
    protected global::System.Web.UI.WebControls.Literal litSuccessMsg;
    protected global::System.Web.UI.WebControls.TextBox txtSearch;
    protected global::System.Web.UI.WebControls.TextBox txtBookNo;
    protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
    protected global::System.Web.UI.WebControls.DropDownList ddlLanguage;
    protected global::System.Web.UI.WebControls.TextBox txtPublisher;
    protected global::System.Web.UI.WebControls.TextBox txtDDC;
    protected global::System.Web.UI.WebControls.CheckBox chkAvailOnly;
    protected global::System.Web.UI.WebControls.Button btnSearch;
    protected global::System.Web.UI.WebControls.Panel pnlResultsTable;
    protected global::System.Web.UI.WebControls.Repeater rptBooks;
    protected global::System.Web.UI.WebControls.LinkButton btnDirectIssue;
    protected global::System.Web.UI.WebControls.Panel pnlPager;
    protected global::System.Web.UI.WebControls.HyperLink lnkPrev;
    protected global::System.Web.UI.WebControls.Repeater rptPager;
    protected global::System.Web.UI.WebControls.HyperLink lnkNext;
    protected global::System.Web.UI.WebControls.Panel pnlEmptyState;
    protected global::System.Web.UI.WebControls.LinkButton btnClearFilters;
}
