//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Pages_Books_BookSearch {
    protected global::System.Web.UI.WebControls.Content cHead;
    protected global::System.Web.UI.WebControls.Content cBody;
    protected global::System.Web.UI.UpdatePanel upBookSearch;
    protected global::System.Web.UI.WebControls.TextBox txtGlobalSearch;
    protected global::System.Web.UI.WebControls.LinkButton lnkClearAll;
    protected global::System.Web.UI.WebControls.TextBox txtAuthor;
    protected global::System.Web.UI.WebControls.TextBox txtBookName;
    protected global::System.Web.UI.WebControls.TextBox txtEdition;
    protected global::System.Web.UI.WebControls.TextBox txtPublisher;
    protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
    protected global::System.Web.UI.WebControls.DropDownList ddlLanguage;
    protected global::System.Web.UI.WebControls.TextBox txtYear;
    protected global::System.Web.UI.WebControls.TextBox txtDDC;
    protected global::System.Web.UI.WebControls.Button btnSearch;
    protected global::System.Web.UI.WebControls.HiddenField hfFiltersState;
    protected global::System.Web.UI.WebControls.Literal litResultsHeader;
    protected global::System.Web.UI.WebControls.Repeater rptBooks;
    protected global::System.Web.UI.WebControls.Repeater rptCopies;
    protected global::System.Web.UI.WebControls.LinkButton btnDirectIssue;
    protected global::System.Web.UI.WebControls.Panel pnlEmptyState;
    protected global::System.Web.UI.WebControls.LinkButton btnClearAllFilters;
    protected global::System.Web.UI.WebControls.Panel pnlBookDetailModal;
    protected global::System.Web.UI.WebControls.Literal litModalTitle;
    protected global::System.Web.UI.WebControls.Literal litModalContent;
    protected global::System.Web.UI.WebControls.Image imgModalCover;
    protected global::System.Web.UI.WebControls.Button btnCloseModal;
}
