//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Pages_Admin_Dashboard {
    protected global::System.Web.UI.WebControls.Content cHead;
    protected global::System.Web.UI.WebControls.Content cBody;
    protected global::System.Web.UI.WebControls.Literal litTotalTitles;
    protected global::System.Web.UI.WebControls.Literal litActiveMembers;
    protected global::System.Web.UI.WebControls.Literal litBooksOut;
    protected global::System.Web.UI.WebControls.Literal litAvailableCopies;
    protected global::System.Web.UI.WebControls.LinkButton lnkOverduesCard;
    protected global::System.Web.UI.WebControls.Literal litOverdue;
    protected global::System.Web.UI.WebControls.Literal litFines;
    protected global::System.Web.UI.WebControls.LinkButton lnkTodayReturnsCard;
    protected global::System.Web.UI.WebControls.Literal litTodayReturns;
    protected global::System.Web.UI.WebControls.Literal litRemindersGentle;
    protected global::System.Web.UI.WebControls.Literal litRemindersHarsh;
    protected global::System.Web.UI.WebControls.Literal litRemindersFinal;
    protected global::System.Web.UI.WebControls.Literal litGridTitle;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl spnBadge;
    protected global::System.Web.UI.WebControls.Literal litOverdueCountBadge;
    protected global::System.Web.UI.WebControls.Repeater rptOverdues;
    protected global::System.Web.UI.WebControls.Panel pnlNoOverdues;
    protected global::System.Web.UI.WebControls.Literal litNoRecordsMsg;
    protected global::System.Web.UI.WebControls.Repeater rptRackOccupancy;
}
