//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Pages_System_DefineFacilityFine {
    protected global::System.Web.UI.WebControls.Content cHead;
    protected global::System.Web.UI.WebControls.Content cBody;
    protected global::System.Web.UI.WebControls.Panel pnlAlert;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAlert;
    protected global::System.Web.UI.WebControls.Literal litAlertMsg;
    protected global::System.Web.UI.WebControls.HiddenField hfActiveTab;
    protected global::System.Web.UI.WebControls.Literal litFacilityFormTitle;
    protected global::System.Web.UI.WebControls.HiddenField hfFacilityID;
    protected global::System.Web.UI.WebControls.TextBox txtFacilityName;
    protected global::System.Web.UI.WebControls.TextBox txtCostPerHour;
    protected global::System.Web.UI.WebControls.CheckBox chkFacilityActive;
    protected global::System.Web.UI.WebControls.Button btnSaveFacility;
    protected global::System.Web.UI.WebControls.Button btnClearFacility;
    protected global::System.Web.UI.WebControls.GridView gvFacilities;
    protected global::System.Web.UI.WebControls.LinkButton btnEdit;
    protected global::System.Web.UI.WebControls.Literal litFineFormTitle;
    protected global::System.Web.UI.WebControls.HiddenField hfReasonID;
    protected global::System.Web.UI.WebControls.TextBox txtReasonName;
    protected global::System.Web.UI.WebControls.TextBox txtDefaultAmount;
    protected global::System.Web.UI.WebControls.Button btnSaveFineReason;
    protected global::System.Web.UI.WebControls.Button btnClearFineReason;
    protected global::System.Web.UI.WebControls.GridView gvFineReasons;
}
