//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Pages_Circulation_IssueReturn {
    protected global::System.Web.UI.WebControls.Content cHead;
    protected global::System.Web.UI.WebControls.Content cBody;
    protected global::System.Web.UI.UpdatePanel upCirculation;
    
    // Alert Controls
    protected global::System.Web.UI.WebControls.Panel pnlAlert;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAlert;
    protected global::System.Web.UI.WebControls.Literal litAlertMsg;

    // Top Shared Member Information Controls
    protected global::System.Web.UI.WebControls.TextBox txtMemberNo;
    protected global::System.Web.UI.WebControls.Button btnVerifyMember;
    protected global::System.Web.UI.WebControls.TextBox txtMemberName;
    protected global::System.Web.UI.WebControls.TextBox txtMembershipType;
    protected global::System.Web.UI.WebControls.TextBox txtMemberStatus;
    protected global::System.Web.UI.WebControls.TextBox txtMembershipStatus;
    protected global::System.Web.UI.WebControls.TextBox txtMaxLoanPeriod;
    protected global::System.Web.UI.WebControls.TextBox txtRenewalsAllowed;
    protected global::System.Web.UI.WebControls.TextBox txtLateFinePerDay;
    protected global::System.Web.UI.WebControls.TextBox txtMaxBookIssue;
    protected global::System.Web.UI.WebControls.TextBox txtAlreadyIssuedM;
    protected global::System.Web.UI.WebControls.TextBox txtAlreadyIssuedMS;
    protected global::System.Web.UI.WebControls.TextBox txtAlreadyIssuedTotal;
    protected global::System.Web.UI.WebControls.Panel pnlAlreadyIssuedSection;
    protected global::System.Web.UI.WebControls.GridView gvMemberActiveLoans;

    // Tab Selector Buttons
    protected global::System.Web.UI.WebControls.Button btnTabIssue;
    protected global::System.Web.UI.WebControls.Button btnTabReturn;
    protected global::System.Web.UI.WebControls.Button btnTabReservation;

    // Mode 1: New Issue Controls
    protected global::System.Web.UI.WebControls.Panel pnlModeIssue;
    protected global::System.Web.UI.WebControls.TextBox txtIssueNo;
    protected global::System.Web.UI.WebControls.TextBox txtIssueDate;
    protected global::System.Web.UI.WebControls.CheckBox chkDirectPrint;
    protected global::System.Web.UI.WebControls.TextBox txtIssueBookNo;
    protected global::System.Web.UI.WebControls.Button btnFetchIssueBook;
    protected global::System.Web.UI.WebControls.TextBox txtIssueBookTitle;
    protected global::System.Web.UI.WebControls.TextBox txtIssueDDC;
    protected global::System.Web.UI.WebControls.TextBox txtIssueReturnDate;
    protected global::System.Web.UI.WebControls.GridView gvIssueBasket;
    protected global::System.Web.UI.WebControls.Button btnIssueRefresh;
    protected global::System.Web.UI.WebControls.Button btnIssueNew;
    protected global::System.Web.UI.WebControls.Button btnSaveIssue;
    protected global::System.Web.UI.WebControls.Button btnIssueClose;

    // Mode 2: Return & Renewal Controls
    protected global::System.Web.UI.WebControls.Panel pnlModeReturn;
    protected global::System.Web.UI.WebControls.TextBox txtReturnMemberNo;
    protected global::System.Web.UI.WebControls.Button btnFetchReturnMember;
    protected global::System.Web.UI.WebControls.TextBox txtReturnBookNo;
    protected global::System.Web.UI.WebControls.Button btnFetchReturnBook;
    protected global::System.Web.UI.WebControls.TextBox txtReturnIssueNoVal;
    protected global::System.Web.UI.WebControls.TextBox txtReturnIssueDateVal;
    protected global::System.Web.UI.WebControls.TextBox txtReturnDueDateVal;
    protected global::System.Web.UI.WebControls.TextBox txtReturnBookTitleVal;
    protected global::System.Web.UI.WebControls.TextBox txtReturnFineVal;
    protected global::System.Web.UI.WebControls.TextBox txtReturnDateVal;
    protected global::System.Web.UI.WebControls.TextBox txtReturnRenewalVal;
    protected global::System.Web.UI.WebControls.TextBox txtReturnDaysLateVal;
    protected global::System.Web.UI.WebControls.GridView gvReturnLoansList;
    protected global::System.Web.UI.WebControls.Button btnReturnRefresh;
    protected global::System.Web.UI.WebControls.Button btnReturnRecheck;
    protected global::System.Web.UI.WebControls.Button btnProcessReturn;
    protected global::System.Web.UI.WebControls.Button btnProcessRenew;

    // Mode 3: Reservation Controls
    protected global::System.Web.UI.WebControls.Panel pnlModeReservation;
    protected global::System.Web.UI.WebControls.TextBox txtResNoVal;
    protected global::System.Web.UI.WebControls.TextBox txtResBookNo;
    protected global::System.Web.UI.WebControls.Button btnFetchResBook;
    protected global::System.Web.UI.WebControls.TextBox txtResDDCVal;
    protected global::System.Web.UI.WebControls.TextBox txtResBookTitleVal;
    protected global::System.Web.UI.WebControls.TextBox txtResDateVal;
    protected global::System.Web.UI.WebControls.TextBox txtResRemarks;
    protected global::System.Web.UI.WebControls.GridView gvReservationsList;
    protected global::System.Web.UI.WebControls.Button btnResRefresh;
    protected global::System.Web.UI.WebControls.Button btnResNew;
    protected global::System.Web.UI.WebControls.Button btnSaveReservation;
    protected global::System.Web.UI.WebControls.Button btnReleaseReservation;

    // Reservation Modal Controls
    protected global::System.Web.UI.WebControls.Panel pnlReservationAlertModal;
    protected global::System.Web.UI.WebControls.Label lblReservedMemberName;
    protected global::System.Web.UI.WebControls.Button btnPrintReservationSlipModal;
    protected global::System.Web.UI.WebControls.Button btnCloseReservationModal;

    // Bottom Menu Controls
    protected global::System.Web.UI.WebControls.DropDownList ddlReportType;
    protected global::System.Web.UI.WebControls.TextBox txtReportAsOnDate;
    protected global::System.Web.UI.WebControls.Button btnPrintReporting;
    protected global::System.Web.UI.WebControls.Button btnPrintLedgerQuick;
    protected global::System.Web.UI.WebControls.Button btnPrintIssuanceQuick;
    protected global::System.Web.UI.WebControls.Button btnPrintOverdueQuick;
    protected global::System.Web.UI.WebControls.Button btnPrintReservationQuick;

    // Confirmation Modal Controls
    protected global::System.Web.UI.WebControls.Panel pnlConfirmAction;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divConfirmBox;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divConfirmIcon;
    protected global::System.Web.UI.WebControls.Literal litConfirmTitle;
    protected global::System.Web.UI.WebControls.Literal litConfirmMsg;
    protected global::System.Web.UI.WebControls.Literal litConfirmDetail;
    protected global::System.Web.UI.WebControls.Button btnConfirmYes;
    protected global::System.Web.UI.WebControls.Button btnConfirmNo;

    // Report Modal Controls
    protected global::System.Web.UI.WebControls.Panel pnlReportModal;
    protected global::System.Web.UI.WebControls.Button btnCloseReportModal;
    protected global::System.Web.UI.WebControls.Literal litReportModalHtml;

    // Hidden Controls
    protected global::System.Web.UI.WebControls.HiddenField hfCircMode;
    protected global::System.Web.UI.WebControls.HiddenField hfConfirmAction;
    protected global::System.Web.UI.WebControls.HiddenField hfConfirmCopyID;
    protected global::System.Web.UI.WebControls.HiddenField hfConfirmLoanID;
    protected global::System.Web.UI.WebControls.Literal litPrintSlipHtml;
}
