//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Pages_Circulation_IssueNote {
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    protected global::System.Web.UI.WebControls.Label lblIssueNo;
    protected global::System.Web.UI.WebControls.Label lblTransactionDateTime;
    protected global::System.Web.UI.WebControls.Label lblIssueTo;
    protected global::System.Web.UI.WebControls.Repeater rptBooks;
    protected global::System.Web.UI.WebControls.Label lblIssuedBySig;
    protected global::System.Web.UI.WebControls.Label lblPrintAudit;
}
