//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Pages_Members_MemberLedger {
    protected global::System.Web.UI.WebControls.Content cHead;
    protected global::System.Web.UI.WebControls.Content cBody;
    protected global::System.Web.UI.UpdatePanel upMemberLedger;
    protected global::System.Web.UI.WebControls.Panel pnlAlert;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAlert;
    protected global::System.Web.UI.WebControls.Literal litAlertMsg;
    protected global::System.Web.UI.WebControls.TextBox txtMemberNo;
    protected global::System.Web.UI.WebControls.TextBox txtMemberName;
    protected global::System.Web.UI.WebControls.TextBox txtStartDate;
    protected global::System.Web.UI.WebControls.TextBox txtEndDate;
    protected global::System.Web.UI.WebControls.DropDownList ddlMonth;
    protected global::System.Web.UI.WebControls.DropDownList ddlYear;
    protected global::System.Web.UI.WebControls.Button btnSearch;
    protected global::System.Web.UI.WebControls.Button btnExportExcel;
    protected global::System.Web.UI.WebControls.Button btnClear;
    protected global::System.Web.UI.WebControls.HiddenField hfSelectedMemberID;
    protected global::System.Web.UI.WebControls.Panel pnlLedgerContent;
    protected global::System.Web.UI.WebControls.Label lblMembershipNo;
    protected global::System.Web.UI.WebControls.Label lblFullName;
    protected global::System.Web.UI.WebControls.Label lblMemberType;
    protected global::System.Web.UI.WebControls.Label lblCNIC;
    protected global::System.Web.UI.WebControls.Label lblPhone;
    protected global::System.Web.UI.WebControls.Label lblEmail;
    protected global::System.Web.UI.WebControls.Label lblJoinDate;
    protected global::System.Web.UI.WebControls.Label lblStatusBadge;
    protected global::System.Web.UI.WebControls.Label lblTotalLoans;
    protected global::System.Web.UI.WebControls.Label lblActiveLoans;
    protected global::System.Web.UI.WebControls.Label lblTotalFines;
    protected global::System.Web.UI.WebControls.Label lblOutstandingBalance;
    protected global::System.Web.UI.WebControls.GridView gvLedger;
    protected global::System.Web.UI.WebControls.Panel pnlEmptyState;
}
