//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymkhanaLibrary {
    
    public partial class MemberAttendance {
        protected global::System.Web.UI.WebControls.Content cHead;
        protected global::System.Web.UI.WebControls.Content cBody;
        protected global::System.Web.UI.WebControls.Label lblTodayVisitors;
        protected global::System.Web.UI.WebControls.Label lblCurrentInside;
        protected global::System.Web.UI.WebControls.Label lblTotalCheckIns;
        protected global::System.Web.UI.WebControls.Label lblTotalCheckOuts;
        protected global::System.Web.UI.WebControls.Label lblAvgStayTime;
        protected global::System.Web.UI.WebControls.Label lblMonthlyVisitors;
        protected global::System.Web.UI.WebControls.Panel pnlAlertMessage;
        protected global::System.Web.UI.WebControls.Label lblAlertText;
        protected global::System.Web.UI.WebControls.DropDownList ddlSearchBy;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.TextBox txtRemarks;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Panel pnlNoMemberSelected;
        protected global::System.Web.UI.WebControls.Panel pnlMemberDetails;
        protected global::System.Web.UI.WebControls.Panel pnlExpiredAlert;
        protected global::System.Web.UI.WebControls.Label lblExpiredAlertText;
        protected global::System.Web.UI.WebControls.Panel pnlCardStatusAlert;
        protected global::System.Web.UI.WebControls.Label lblCardStatusAlertText;
        protected global::System.Web.UI.WebControls.Panel pnlAccountStatusAlert;
        protected global::System.Web.UI.WebControls.Label lblAccountStatusAlertText;
        protected global::System.Web.UI.WebControls.Panel pnlInactiveAlert;
        protected global::System.Web.UI.WebControls.Panel pnlFineAlert;
        protected global::System.Web.UI.WebControls.Label lblMemberIdVal;
        protected global::System.Web.UI.WebControls.HiddenField hfMemberID;
        protected global::System.Web.UI.WebControls.Label lblMemberNoVal;
        protected global::System.Web.UI.WebControls.Label lblMemberNameVal;
        protected global::System.Web.UI.WebControls.Label lblMemberTypeVal;
        protected global::System.Web.UI.WebControls.Label lblPhoneVal;
        protected global::System.Web.UI.WebControls.Label lblEmailVal;
        protected global::System.Web.UI.WebControls.Label lblExpiryVal;
        protected global::System.Web.UI.WebControls.Label lblFineVal;
        protected global::System.Web.UI.WebControls.Label lblBooksVal;
        protected global::System.Web.UI.WebControls.Label lblStatusVal;
        protected global::System.Web.UI.WebControls.Button btnCheckIn;
        protected global::System.Web.UI.WebControls.Button btnCheckOut;
        protected global::System.Web.UI.WebControls.GridView gvCurrentVisitors;
        protected global::System.Web.UI.WebControls.Button btnGvCheckout;
        protected global::System.Web.UI.WebControls.GridView gvTodayAttendance;
        protected global::System.Web.UI.WebControls.Button btnGoToHistory;
    }
}
