//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymkhanaLibrary {
    
    public partial class MultipleBooksWeedout {
        protected global::System.Web.UI.WebControls.Content cHead;
        protected global::System.Web.UI.WebControls.Content cBody;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.Label lblAlert;
        protected global::System.Web.UI.WebControls.RadioButton rdoSearchTitle;
        protected global::System.Web.UI.WebControls.RadioButton rdoAddCopy;
        protected global::System.Web.UI.WebControls.Panel pnlSearchTitleBlock;
        protected global::System.Web.UI.WebControls.TextBox txtSearchBook;
        protected global::System.Web.UI.WebControls.Button btnSearchBook;
        protected global::System.Web.UI.WebControls.Panel pnlAddCopyBlock;
        protected global::System.Web.UI.WebControls.TextBox txtCopyBookNo;
        protected global::System.Web.UI.WebControls.Button btnAddCopy;
        protected global::System.Web.UI.WebControls.Panel pnlSearchResults;
        protected global::System.Web.UI.WebControls.GridView gvBooks;
        protected global::System.Web.UI.WebControls.LinkButton lnkAdd;
        protected global::System.Web.UI.WebControls.Panel pnlSelectedBooks;
        protected global::System.Web.UI.WebControls.GridView gvSelectedBooks;
        protected global::System.Web.UI.WebControls.Label lblLoanStatus;
        protected global::System.Web.UI.WebControls.LinkButton lnkRemove;
        protected global::System.Web.UI.WebControls.Button btnWeedAllSelected;
    }
}
