//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Pages_OverdueManagement {
    protected global::System.Web.UI.WebControls.Content cHead;
    protected global::System.Web.UI.WebControls.Content cBody;
    protected global::System.Web.UI.WebControls.Panel pnlAlert;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAlert;
    protected global::System.Web.UI.WebControls.Literal litAlertMsg;
    protected global::System.Web.UI.WebControls.Button btnTabReminders;
    protected global::System.Web.UI.WebControls.Button btnTabReversals;
    protected global::System.Web.UI.WebControls.HiddenField hfActiveTab;
    protected global::System.Web.UI.WebControls.Panel pnlTabReminders;
    protected global::System.Web.UI.WebControls.DropDownList ddlScenarioFilter;
    protected global::System.Web.UI.WebControls.TextBox txtSearchReminders;
    protected global::System.Web.UI.WebControls.Button btnRefreshReminders;
    protected global::System.Web.UI.WebControls.GridView gvReminders;
    protected global::System.Web.UI.WebControls.LinkButton btnGenerate;
    protected global::System.Web.UI.WebControls.LinkButton btnMarkSent;
    protected global::System.Web.UI.WebControls.Panel pnlTabReversals;
    protected global::System.Web.UI.WebControls.TextBox txtSearchReversals;
    protected global::System.Web.UI.WebControls.Button btnRefreshReversals;
    protected global::System.Web.UI.WebControls.GridView gvReversals;
    protected global::System.Web.UI.WebControls.LinkButton btnReverse;
    protected global::System.Web.UI.WebControls.Panel pnlLetterModal;
    protected global::System.Web.UI.WebControls.Button btnCloseLetter;
    protected global::System.Web.UI.WebControls.Literal litPrintableLetter;
    protected global::System.Web.UI.WebControls.PlaceHolder phOldControls;
    protected global::System.Web.UI.WebControls.Literal litLetterRef;
    protected global::System.Web.UI.WebControls.Literal litLetterMemberName;
    protected global::System.Web.UI.WebControls.Literal litLetterMemberNo;
    protected global::System.Web.UI.WebControls.Literal litLetterMemberAddress;
    protected global::System.Web.UI.WebControls.Literal litLetterSubject;
    protected global::System.Web.UI.WebControls.Literal litLetterMainBody;
    protected global::System.Web.UI.WebControls.Literal litLetterBookTitle;
    protected global::System.Web.UI.WebControls.Literal litLetterBarcode;
    protected global::System.Web.UI.WebControls.Literal litLetterIssueDate;
    protected global::System.Web.UI.WebControls.Literal litLetterDueDate;
    protected global::System.Web.UI.WebControls.Literal litLetterOverdueDays;
    protected global::System.Web.UI.WebControls.PlaceHolder phFinancialDetails;
    protected global::System.Web.UI.WebControls.Literal litDaysFineCount;
    protected global::System.Web.UI.WebControls.Literal litDaysFineAmt;
    protected global::System.Web.UI.WebControls.Literal litBookCostAmt;
    protected global::System.Web.UI.WebControls.Literal litPenaltyAmt;
    protected global::System.Web.UI.WebControls.Literal litTotalLiabAmt;
    protected global::System.Web.UI.WebControls.Button btnCloseLetterFooter;
    protected global::System.Web.UI.WebControls.Panel pnlVoucherModal;
    protected global::System.Web.UI.WebControls.Button btnCloseVoucher;
    protected global::System.Web.UI.WebControls.Literal litVoucherNo;
    protected global::System.Web.UI.WebControls.Literal litVoucherMemberName;
    protected global::System.Web.UI.WebControls.Literal litVoucherMemberNo;
    protected global::System.Web.UI.WebControls.Literal litVoucherOverdueFineAmt;
    protected global::System.Web.UI.WebControls.Literal litVoucherNetPayable;
    protected global::System.Web.UI.WebControls.Button btnCloseVoucherFooter;
}
