//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymkhanaLibrary {
    
    public partial class ReportsPanel {
        protected global::System.Web.UI.WebControls.Content cHead;
        protected global::System.Web.UI.WebControls.Content cBody;
        protected global::System.Web.UI.WebControls.Literal litPrintFilters;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.Literal litAlertMsg;
        protected global::System.Web.UI.WebControls.HiddenField hfActiveTab;
        protected global::System.Web.UI.WebControls.HiddenField hfPrintData;
        protected global::System.Web.UI.WebControls.HiddenField hfPrintType;
        protected global::System.Web.UI.WebControls.TextBox txtCatBookNoFrom;
        protected global::System.Web.UI.WebControls.TextBox txtCatBookNoTo;
        protected global::System.Web.UI.WebControls.DropDownList ddlCatLanguage;
        protected global::System.Web.UI.WebControls.DropDownList ddlCatBookType;
        protected global::System.Web.UI.WebControls.DropDownList ddlCatCondition;
        protected global::System.Web.UI.WebControls.DropDownList ddlCatAvailability;
        protected global::System.Web.UI.WebControls.Button btnGenCatalogue;
        protected global::System.Web.UI.WebControls.Button btnExportCatalogue;
        protected global::System.Web.UI.WebControls.Button btnPDFCatalogue;
        protected global::System.Web.UI.WebControls.Literal litCatalogueCount;
        protected global::System.Web.UI.WebControls.GridView gvCatalogue;
        protected global::System.Web.UI.WebControls.TextBox txtLabelBookNoFrom;
        protected global::System.Web.UI.WebControls.TextBox txtLabelBookNoTo;
        protected global::System.Web.UI.WebControls.Button btnGenLabels;
        protected global::System.Web.UI.WebControls.Button btnPrintLabels;
        protected global::System.Web.UI.WebControls.Literal litLabelsCount;
        protected global::System.Web.UI.WebControls.GridView gvLabels;
        protected global::System.Web.UI.WebControls.TextBox txtRegBookNoFrom;
        protected global::System.Web.UI.WebControls.TextBox txtRegBookNoTo;
        protected global::System.Web.UI.WebControls.Button btnGenRegulations;
        protected global::System.Web.UI.WebControls.Button btnPrintRegulations;
        protected global::System.Web.UI.WebControls.Literal litRegulationsCount;
        protected global::System.Web.UI.WebControls.GridView gvRegulations;
        protected global::System.Web.UI.WebControls.TextBox txtIssueFrom;
        protected global::System.Web.UI.WebControls.TextBox txtIssueTo;
        protected global::System.Web.UI.WebControls.DropDownList ddlIssueType;
        protected global::System.Web.UI.WebControls.TextBox txtIssueMemberNo;
        protected global::System.Web.UI.WebControls.Button btnGenIssuance;
        protected global::System.Web.UI.WebControls.Button btnExportIssuance;
        protected global::System.Web.UI.WebControls.Button btnPDFIssuance;
        protected global::System.Web.UI.WebControls.Literal litIssuancesCount;
        protected global::System.Web.UI.WebControls.GridView gvIssuances;
        protected global::System.Web.UI.WebControls.TextBox txtReturnFrom;
        protected global::System.Web.UI.WebControls.TextBox txtReturnTo;
        protected global::System.Web.UI.WebControls.Button btnGenReturns;
        protected global::System.Web.UI.WebControls.Button btnExportReturns;
        protected global::System.Web.UI.WebControls.Button btnPDFReturns;
        protected global::System.Web.UI.WebControls.Literal litReturnsCount;
        protected global::System.Web.UI.WebControls.GridView gvReturns;
        protected global::System.Web.UI.WebControls.TextBox txtReserveBookNo;
        protected global::System.Web.UI.WebControls.TextBox txtReserveMemberNo;
        protected global::System.Web.UI.WebControls.Button btnGenReservations;
        protected global::System.Web.UI.WebControls.Button btnExportReservations;
        protected global::System.Web.UI.WebControls.Button btnPDFReservations;
        protected global::System.Web.UI.WebControls.Literal litReservationsCount;
        protected global::System.Web.UI.WebControls.GridView gvReservations;
        protected global::System.Web.UI.WebControls.TextBox txtAuditBookNoFrom;
        protected global::System.Web.UI.WebControls.TextBox txtAuditBookNoTo;
        protected global::System.Web.UI.WebControls.DropDownList ddlAuditLanguage;
        protected global::System.Web.UI.WebControls.DropDownList ddlAuditCondition;
        protected global::System.Web.UI.WebControls.TextBox txtAuditAcqFrom;
        protected global::System.Web.UI.WebControls.TextBox txtAuditAcqTo;
        protected global::System.Web.UI.WebControls.TextBox txtAuditSource;
        protected global::System.Web.UI.WebControls.Button btnGenCostAudit;
        protected global::System.Web.UI.WebControls.Button btnExportCostAudit;
        protected global::System.Web.UI.WebControls.Button btnPDFCostAudit;
        protected global::System.Web.UI.WebControls.Literal litCostAuditCount;
        protected global::System.Web.UI.WebControls.GridView gvCostAudit;
        protected global::System.Web.UI.WebControls.Literal litTriggerPrint;
    }
}
