//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Pages_Circulation_Reservations {
    protected global::System.Web.UI.WebControls.Content cHead;
    protected global::System.Web.UI.WebControls.Content cBody;
    protected global::System.Web.UI.UpdatePanel upReservations;
    protected global::System.Web.UI.WebControls.Panel pnlAlert;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAlert;
    protected global::System.Web.UI.WebControls.Literal litAlertMsg;
    protected global::System.Web.UI.WebControls.TextBox txtMemberSearch;
    protected global::System.Web.UI.WebControls.Button btnSearchMember;
    protected global::System.Web.UI.WebControls.DropDownList ddlMember;
    protected global::System.Web.UI.WebControls.TextBox txtMemberName;
    protected global::System.Web.UI.WebControls.TextBox txtBookSearch;
    protected global::System.Web.UI.WebControls.Button btnSearchBook;
    protected global::System.Web.UI.WebControls.DropDownList ddlBookCatalog;
    protected global::System.Web.UI.WebControls.TextBox txtStartDate;
    protected global::System.Web.UI.WebControls.TextBox txtEndDate;
    protected global::System.Web.UI.WebControls.Panel pnlForecastPreview;
    protected global::System.Web.UI.WebControls.Label lblTotalCopies;
    protected global::System.Web.UI.WebControls.Label lblAvailableCopies;
    protected global::System.Web.UI.WebControls.Label lblQueueSize;
    protected global::System.Web.UI.WebControls.Label lblForecastDate;
    protected global::System.Web.UI.WebControls.Button btnAddToBasket;
    protected global::System.Web.UI.WebControls.Button btnRefresh;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlBasketSection;
    protected global::System.Web.UI.WebControls.GridView gvBasket;
    protected global::System.Web.UI.WebControls.LinkButton btnRemove;
    protected global::System.Web.UI.WebControls.Panel pnlBasketEmpty;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divConfirmReservations;
    protected global::System.Web.UI.WebControls.Button btnPlaceReservation;
    protected global::System.Web.UI.WebControls.Label lblTotalActiveReservations;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterBook;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterMember;
    protected global::System.Web.UI.WebControls.Button btnClearFilters;
    protected global::System.Web.UI.WebControls.GridView gvReservations;
    protected global::System.Web.UI.WebControls.Label lblForecast;
    protected global::System.Web.UI.WebControls.LinkButton btnMoveUp;
    protected global::System.Web.UI.WebControls.LinkButton btnMoveDown;
    protected global::System.Web.UI.WebControls.LinkButton btnIssueDirect;
    protected global::System.Web.UI.WebControls.LinkButton btnPrintSlip;
    protected global::System.Web.UI.WebControls.LinkButton btnCancel;
    protected global::System.Web.UI.WebControls.Panel pnlIssueDirect;
    protected global::System.Web.UI.WebControls.LinkButton btnCancelIssueDirectTop;
    protected global::System.Web.UI.WebControls.HiddenField hdnIssueResID;
    protected global::System.Web.UI.WebControls.HiddenField hdnIssueMemberID;
    protected global::System.Web.UI.WebControls.HiddenField hdnIssueBookID;
    protected global::System.Web.UI.WebControls.HiddenField hdnIssueBorrowerNo;
    protected global::System.Web.UI.WebControls.HiddenField hdnIssueBorrowerName;
    protected global::System.Web.UI.WebControls.Label lblIssueMemberName;
    protected global::System.Web.UI.WebControls.Label lblIssueBookTitle;
    protected global::System.Web.UI.WebControls.DropDownList ddlIssueCopies;
    protected global::System.Web.UI.WebControls.Button btnConfirmIssueDirect;
    protected global::System.Web.UI.WebControls.Button btnCancelIssueDirect;
    protected global::System.Web.UI.WebControls.Panel pnlReserveSlipModal;
    protected global::System.Web.UI.WebControls.Button btnCloseReserveSlip;
    protected global::System.Web.UI.WebControls.Literal litPrintableReserveSlip;
    protected global::System.Web.UI.WebControls.Button btnCloseReserveSlipFooter;
}
