//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Pages_Circulation_ReturnBook {
    protected global::System.Web.UI.WebControls.Content cHead;
    protected global::System.Web.UI.WebControls.Content cBody;
    protected global::System.Web.UI.UpdatePanel upReturnDesk;
    protected global::System.Web.UI.WebControls.Panel pnlAlert;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAlert;
    protected global::System.Web.UI.WebControls.Literal litAlertMsg;
    protected global::System.Web.UI.WebControls.Panel pnlPolicyWarning;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divPolicyWarning;
    protected global::System.Web.UI.WebControls.Literal litPolicyWarningMsg;
    protected global::System.Web.UI.WebControls.TextBox txtReturnBarcode;
    protected global::System.Web.UI.WebControls.TextBox txtReturnIssueNo;
    protected global::System.Web.UI.WebControls.TextBox txtReturnMemberSearch;
    protected global::System.Web.UI.WebControls.Button btnSearchReturnMember;
    protected global::System.Web.UI.WebControls.DropDownList ddlReturnMemberLookup;
    protected global::System.Web.UI.WebControls.Panel pnlActiveLoansGridContainer;
    protected global::System.Web.UI.WebControls.GridView gvActiveLoans;
    protected global::System.Web.UI.WebControls.LinkButton btnGridReturn;
    protected global::System.Web.UI.WebControls.LinkButton btnGridReissue;
    protected global::System.Web.UI.WebControls.DropDownList ddlReturnCondition;
    protected global::System.Web.UI.WebControls.TextBox txtReturnDate;
    protected global::System.Web.UI.WebControls.TextBox txtReturnTime;
    protected global::System.Web.UI.WebControls.Panel pnlReservationAlertModal;
    protected global::System.Web.UI.WebControls.Label lblReservedMemberName;
    protected global::System.Web.UI.WebControls.Button btnPrintReservationSlip;
    protected global::System.Web.UI.WebControls.Button btnCloseReservationModal;
}
