//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Pages_Stock_StockTracking {

    protected global::System.Web.UI.WebControls.HiddenField hfActiveTab;

    protected global::System.Web.UI.UpdatePanel upStockTracking;

    protected global::System.Web.UI.WebControls.Panel pnlAlert;

    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAlert;

    protected global::System.Web.UI.WebControls.Literal litAlertMsg;

    protected global::System.Web.UI.WebControls.Literal litStatTitles;

    protected global::System.Web.UI.WebControls.Literal litStatCopies;

    protected global::System.Web.UI.WebControls.Literal litStatAvailable;

    protected global::System.Web.UI.WebControls.Literal litStatIssued;

    protected global::System.Web.UI.WebControls.Literal litStatReserved;

    protected global::System.Web.UI.WebControls.Literal litStatOverdue;

    protected global::System.Web.UI.WebControls.Literal litStatLost;

    protected global::System.Web.UI.WebControls.Literal litStatDamaged;

    protected global::System.Web.UI.WebControls.Literal litStatMissing;

    protected global::System.Web.UI.WebControls.Literal litStatWithdrawn;

    protected global::System.Web.UI.WebControls.TextBox txtFilterTitle;

    protected global::System.Web.UI.WebControls.TextBox txtFilterAcqNo;

    protected global::System.Web.UI.WebControls.TextBox txtFilterBookNo;

    protected global::System.Web.UI.WebControls.TextBox txtFilterBarcode;

    protected global::System.Web.UI.WebControls.TextBox txtFilterISBN;

    protected global::System.Web.UI.WebControls.TextBox txtFilterAuthor;

    protected global::System.Web.UI.WebControls.DropDownList ddlFilterCategory;

    protected global::System.Web.UI.WebControls.TextBox txtFilterSubject;

    protected global::System.Web.UI.WebControls.DropDownList ddlFilterLanguage;

    protected global::System.Web.UI.WebControls.TextBox txtFilterPublisher;

    protected global::System.Web.UI.WebControls.TextBox txtFilterDDC;

    protected global::System.Web.UI.WebControls.DropDownList ddlFilterHall;

    protected global::System.Web.UI.WebControls.DropDownList ddlFilterFloor;

    protected global::System.Web.UI.WebControls.TextBox txtFilterSection;

    protected global::System.Web.UI.WebControls.DropDownList ddlFilterRack;

    protected global::System.Web.UI.WebControls.TextBox txtFilterSlot;

    protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;

    protected global::System.Web.UI.WebControls.TextBox txtFilterDateFrom;

    protected global::System.Web.UI.WebControls.TextBox txtFilterDateTo;

    protected global::System.Web.UI.WebControls.LinkButton btnApplyFilters;

    protected global::System.Web.UI.WebControls.LinkButton btnClearFilters;

    protected global::System.Web.UI.WebControls.Literal litGridRecordCount;

    protected global::System.Web.UI.WebControls.GridView gvStock;

    protected global::System.Web.UI.WebControls.Panel pnlStartAuditSession;

    protected global::System.Web.UI.WebControls.TextBox txtAuditSessionName;

    protected global::System.Web.UI.WebControls.DropDownList ddlAuditScope;

    protected global::System.Web.UI.WebControls.TextBox txtAuditRemarks;

    protected global::System.Web.UI.WebControls.Button btnStartAudit;

    protected global::System.Web.UI.WebControls.Panel pnlActiveAuditWorkflow;

    protected global::System.Web.UI.WebControls.Literal litActiveSessionName;

    protected global::System.Web.UI.WebControls.Literal litActiveSessionDate;

    protected global::System.Web.UI.WebControls.LinkButton btnViewActiveReport;

    protected global::System.Web.UI.WebControls.LinkButton btnViewActiveMissingReport;

    protected global::System.Web.UI.WebControls.Button btnCompleteAudit;

    protected global::System.Web.UI.WebControls.Button btnCancelAudit;

    protected global::System.Web.UI.WebControls.TextBox txtScanBarcode;

    protected global::System.Web.UI.WebControls.Button btnVerifyManual;

    protected global::System.Web.UI.WebControls.Label lblScanFeedback;

    protected global::System.Web.UI.WebControls.Literal litAuditProgressPct;

    protected global::System.Web.UI.WebControls.Literal litAuditProgressRatio;

    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAuditProgressBar;

    protected global::System.Web.UI.WebControls.Literal litAuditCountExpected;

    protected global::System.Web.UI.WebControls.Literal litAuditCountMatches;

    protected global::System.Web.UI.WebControls.Literal litAuditCountMisplaced;

    protected global::System.Web.UI.WebControls.Literal litAuditCountMissing;

    protected global::System.Web.UI.WebControls.Panel pnlReconcileNoActiveSession;

    protected global::System.Web.UI.WebControls.Panel pnlReconcileActiveSession;

    protected global::System.Web.UI.WebControls.Button btnMarkSelectedMissing;

    protected global::System.Web.UI.WebControls.Button btnMarkAllMissing;

    protected global::System.Web.UI.WebControls.Literal litReconcileSummaryText;

    protected global::System.Web.UI.WebControls.GridView gvReconcileMissing;

    protected global::System.Web.UI.WebControls.GridView gvAuditVerified;

    protected global::System.Web.UI.WebControls.DropDownList ddlReportType;

    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divReportFilterVal;

    protected global::System.Web.UI.WebControls.TextBox txtReportFilterVal;

    protected global::System.Web.UI.WebControls.Button btnGenerateReport;

    protected global::System.Web.UI.WebControls.Literal litReportTitle;

    protected global::System.Web.UI.WebControls.Literal litReportCount;

    protected global::System.Web.UI.WebControls.LinkButton btnExportExcel;

    protected global::System.Web.UI.WebControls.LinkButton btnExportCSV;

    protected global::System.Web.UI.WebControls.GridView gvReports;

    protected global::System.Web.UI.WebControls.Panel pnlDetailModal;

    protected global::System.Web.UI.WebControls.LinkButton btnCloseDetailModal;

    protected global::System.Web.UI.WebControls.Literal litModalCover;

    protected global::System.Web.UI.WebControls.Label lblModalTitle;

    protected global::System.Web.UI.WebControls.Label lblModalAuthor;

    protected global::System.Web.UI.WebControls.Label lblModalBarcode;

    protected global::System.Web.UI.WebControls.Label lblModalISBN;

    protected global::System.Web.UI.WebControls.Label lblModalCategory;

    protected global::System.Web.UI.WebControls.Label lblModalPublisher;

    protected global::System.Web.UI.WebControls.Label lblModalAcqDate;

    protected global::System.Web.UI.WebControls.Label lblModalAcqCost;

    protected global::System.Web.UI.WebControls.Label lblModalDDC;

    protected global::System.Web.UI.WebControls.Label lblModalAcqNo;

    protected global::System.Web.UI.WebControls.Label lblModalIsReference;

    protected global::System.Web.UI.WebControls.Label lblModalCondition;

    protected global::System.Web.UI.WebControls.Label lblModalNotes;

    protected global::System.Web.UI.WebControls.Label lblModalLocationHall;

    protected global::System.Web.UI.WebControls.Label lblModalLocationDetails;

    protected global::System.Web.UI.WebControls.Literal litModalStatusBadge;

    protected global::System.Web.UI.WebControls.Panel pnlModalActiveLoan;

    protected global::System.Web.UI.WebControls.Label lblModalLoanMember;

    protected global::System.Web.UI.WebControls.Label lblModalLoanMemberNo;

    protected global::System.Web.UI.WebControls.Label lblModalLoanIssueDate;

    protected global::System.Web.UI.WebControls.Label lblModalLoanDueDate;

    protected global::System.Web.UI.WebControls.Label lblModalLoanRenewals;

    protected global::System.Web.UI.WebControls.Label lblModalLoanStatus;

    protected global::System.Web.UI.WebControls.GridView gvModalLoanHistory;

    protected global::System.Web.UI.WebControls.GridView gvModalLocationHistory;

    protected global::System.Web.UI.WebControls.GridView gvModalWeedingHistory;

    protected global::System.Web.UI.WebControls.Button btnCloseDetail;

    protected global::System.Web.UI.WebControls.Panel pnlTransferModal;

    protected global::System.Web.UI.WebControls.LinkButton btnCloseTransferModal;

    protected global::System.Web.UI.WebControls.Label lblTransferBarcode;

    protected global::System.Web.UI.WebControls.Label lblTransferTitle;

    protected global::System.Web.UI.WebControls.DropDownList ddlTransferHall;

    protected global::System.Web.UI.WebControls.DropDownList ddlTransferUnit;

    protected global::System.Web.UI.WebControls.DropDownList ddlTransferRack;

    protected global::System.Web.UI.WebControls.TextBox txtTransferSlot;

    protected global::System.Web.UI.WebControls.TextBox txtTransferRemarks;

    protected global::System.Web.UI.WebControls.Button btnCancelTransfer;

    protected global::System.Web.UI.WebControls.Button btnSubmitTransfer;

    protected global::System.Web.UI.WebControls.Panel pnlStatusModal;

    protected global::System.Web.UI.WebControls.LinkButton btnCloseStatusModal;

    protected global::System.Web.UI.WebControls.Label lblStatusBarcode;

    protected global::System.Web.UI.WebControls.Label lblStatusTitle;

    protected global::System.Web.UI.WebControls.DropDownList ddlStatusCondition;

    protected global::System.Web.UI.WebControls.CheckBox chkStatusAvailable;

    protected global::System.Web.UI.WebControls.TextBox txtStatusRemarks;

    protected global::System.Web.UI.WebControls.Button btnCancelStatus;

    protected global::System.Web.UI.WebControls.Button btnSubmitStatus;

    protected global::System.Web.UI.WebControls.Panel pnlBarcodeModal;

    protected global::System.Web.UI.WebControls.LinkButton btnCloseBarcodeModal;

    protected global::System.Web.UI.WebControls.Label lblPrintLabelTitle;

    protected global::System.Web.UI.WebControls.Label lblPrintLabelBarcode;

    protected global::System.Web.UI.WebControls.Label lblPrintLabelLocation;

    protected global::System.Web.UI.WebControls.Label lblPrintLabelAcqNo;

    protected global::System.Web.UI.WebControls.Button btnCloseBarcode;

    protected global::System.Web.UI.WebControls.HiddenField hfActiveSessionID;
}
