//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymkhanaLibrary {
    
    public partial class Weedout {
        protected global::System.Web.UI.WebControls.Content cHead;
        protected global::System.Web.UI.WebControls.Content cBody;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.Label lblAlert;
        protected global::System.Web.UI.WebControls.TextBox txtSearchBook;
        protected global::System.Web.UI.WebControls.Button btnSearchBook;
        protected global::System.Web.UI.WebControls.Panel pnlSearchResults;
        protected global::System.Web.UI.WebControls.GridView gvBooks;
        protected global::System.Web.UI.WebControls.LinkButton lnkSelect;
        protected global::System.Web.UI.WebControls.Panel pnlManageWeeding;
        protected global::System.Web.UI.WebControls.Label lblBookTitle;
        protected global::System.Web.UI.WebControls.Label lblBookISBN;
        protected global::System.Web.UI.WebControls.Label lblBookCategory;
        protected global::System.Web.UI.WebControls.Label lblBookEdition;
        protected global::System.Web.UI.WebControls.Label lblBookClassNo;
        protected global::System.Web.UI.WebControls.Label lblTotalCopies;
        protected global::System.Web.UI.WebControls.Label lblAvailableCopies;
        protected global::System.Web.UI.WebControls.GridView gvCopies;
        protected global::System.Web.UI.WebControls.LinkButton lnkWeedCopy;
        protected global::System.Web.UI.WebControls.LinkButton lnkRestoreCopy;
        protected global::System.Web.UI.WebControls.TextBox txtBulkRemarks;
        protected global::System.Web.UI.WebControls.Button btnBulkWeed;
        protected global::System.Web.UI.WebControls.Panel pnlWeedIndividual;
        protected global::System.Web.UI.WebControls.HiddenField hfWeedCopyID;
        protected global::System.Web.UI.WebControls.Label lblWeedBarcode;
        protected global::System.Web.UI.WebControls.TextBox txtWeedRemarks;
        protected global::System.Web.UI.WebControls.Button btnConfirmWeed;
        protected global::System.Web.UI.WebControls.Button btnCancelWeed;
        protected global::System.Web.UI.WebControls.Panel pnlRestoreCopy;
        protected global::System.Web.UI.WebControls.HiddenField hfRestoreCopyID;
        protected global::System.Web.UI.WebControls.Label lblRestoreBarcode;
        protected global::System.Web.UI.WebControls.DropDownList ddlRestoreCondition;
        protected global::System.Web.UI.WebControls.DropDownList ddlHall;
        protected global::System.Web.UI.WebControls.DropDownList ddlAisle;
        protected global::System.Web.UI.WebControls.DropDownList ddlShelfUnit;
        protected global::System.Web.UI.WebControls.DropDownList ddlRack;
        protected global::System.Web.UI.WebControls.DropDownList ddlSlot;
        protected global::System.Web.UI.WebControls.TextBox txtRestoreRemarks;
        protected global::System.Web.UI.WebControls.Button btnConfirmRestore;
        protected global::System.Web.UI.WebControls.Button btnCancelRestore;
    }
}
