//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuestRoomApp.GuestRoomM {
    
    public partial class CancelRoomReservation {
        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblFilterMemberNo;
        protected global::System.Web.UI.WebControls.TextBox txtFilterMemberNo;
        protected global::System.Web.UI.WebControls.Label lblFilterDept;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterDept;
        protected global::System.Web.UI.WebControls.Label lblFilterSubDept;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterSubDept;
        protected global::System.Web.UI.WebControls.Label lblFromDate;
        protected global::System.Web.UI.WebControls.TextBox txtFromDate;
        protected global::System.Web.UI.WebControls.Label lblToDate;
        protected global::System.Web.UI.WebControls.TextBox txtToDate;
        protected global::System.Web.UI.WebControls.Label lblFilterFeedback;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterFeedback;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.GridView gvComplaints;
        protected global::System.Web.UI.WebControls.Literal litQA;
    }
}
