//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefundFee {
    
    public partial class AdminComplaint {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Literal litMode;
        protected global::System.Web.UI.WebControls.HiddenField hfQuestionId;
        protected global::System.Web.UI.WebControls.Label lblDept;
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartment;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDept;
        protected global::System.Web.UI.WebControls.Label lblSubDept;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubDepartment;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSubDept;
        protected global::System.Web.UI.WebControls.Label lblQuestionText;
        protected global::System.Web.UI.WebControls.TextBox txtQuestionText;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvQuestion;
        protected global::System.Web.UI.WebControls.Label lblType;
        protected global::System.Web.UI.WebControls.DropDownList ddlQuestionType;
        protected global::System.Web.UI.WebControls.Panel pnlOptions;
        protected global::System.Web.UI.WebControls.GridView gvOptions;
        protected global::System.Web.UI.WebControls.TextBox txtOptionText;
        protected global::System.Web.UI.WebControls.HiddenField hfOptId;
        protected global::System.Web.UI.WebControls.CheckBox chkIsDeleted;
        protected global::System.Web.UI.WebControls.TextBox txtNewOption;
        protected global::System.Web.UI.WebControls.Button btnAddOption;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.GridView gvQuestions;
        protected global::System.Web.UI.WebControls.Button btnEdit;
        protected global::System.Web.UI.WebControls.Button btnDelete;
    }
}
