//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymkhanaLibrary {
    
    public partial class Pages_ComplaintPanel {
        protected global::System.Web.UI.WebControls.Content Content1;
        protected global::System.Web.UI.WebControls.Content Content2;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.DropDownList ddlDeptFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubDeptFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlTypeFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        protected global::System.Web.UI.WebControls.TextBox txtFromDate;
        protected global::System.Web.UI.WebControls.TextBox txtToDate;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.GridView gvComplaints;
        protected global::System.Web.UI.WebControls.LinkButton lnkAction;
        protected global::System.Web.UI.WebControls.Panel pnlAction;
        protected global::System.Web.UI.WebControls.HiddenField hfComplaintID;
        protected global::System.Web.UI.WebControls.HiddenField hfRecordType;
        protected global::System.Web.UI.WebControls.HiddenField hfMemberNo;
        protected global::System.Web.UI.WebControls.HiddenField hfMemberName;
        protected global::System.Web.UI.WebControls.HiddenField hfMemberEmail;
        protected global::System.Web.UI.WebControls.HiddenField hfMemberPhone;
        protected global::System.Web.UI.WebControls.HiddenField hfDepartmentName;
        protected global::System.Web.UI.WebControls.HiddenField hfSubDepartmentName;
        protected global::System.Web.UI.WebControls.HiddenField hfLocationName;
        protected global::System.Web.UI.WebControls.HiddenField hfCreatedDate;
        protected global::System.Web.UI.WebControls.Literal litCompSubject;
        protected global::System.Web.UI.WebControls.Literal litCompMember;
        protected global::System.Web.UI.WebControls.Literal litCompLocation;
        protected global::System.Web.UI.WebControls.Literal litCompDetail;
        protected global::System.Web.UI.WebControls.DropDownList ddlUpdateStatus;
        protected global::System.Web.UI.WebControls.TextBox txtRemarks;
        protected global::System.Web.UI.WebControls.Button btnSaveStatus;
        protected global::System.Web.UI.WebControls.Button btnCancelAction;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseModal;
    }
}
