//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymkhanaLibrary {
    
    public partial class Pages_ComplaintDashboard {
        protected global::System.Web.UI.WebControls.Content cHead;
        protected global::System.Web.UI.WebControls.Content cBody;
        protected global::System.Web.UI.WebControls.Literal litMemberComplaints;
        protected global::System.Web.UI.WebControls.Literal litMemberFeedbacks;
        protected global::System.Web.UI.WebControls.Literal litPendingCount;
        protected global::System.Web.UI.WebControls.Literal litProgressCount;
        protected global::System.Web.UI.WebControls.Literal litResolutionRate;
        protected global::System.Web.UI.WebControls.GridView gvRecentComplaints;
        protected global::System.Web.UI.WebControls.LinkButton lnkManage;
    }
}
