//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymkhanaLibrary {
    
    public partial class Pages_DefineFeedback {
        protected global::System.Web.UI.WebControls.Content Content1;
        protected global::System.Web.UI.WebControls.Content Content2;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.Literal litFormTitle;
        protected global::System.Web.UI.WebControls.HiddenField hfQuestionID;
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartment;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubDepartment;
        protected global::System.Web.UI.WebControls.DropDownList ddlLocation;
        protected global::System.Web.UI.WebControls.LinkButton btnAddLocation;
        protected global::System.Web.UI.WebControls.TextBox txtQuestionText;
        protected global::System.Web.UI.WebControls.DropDownList ddlQuestionType;
        protected global::System.Web.UI.WebControls.Panel pnlOptions;
        protected global::System.Web.UI.WebControls.TextBox txtOptions;
        protected global::System.Web.UI.WebControls.CheckBox chkActive;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Repeater rptSubDeptGroups;
        protected global::System.Web.UI.WebControls.GridView gvSubQuestions;
        protected global::System.Web.UI.WebControls.LinkButton lnkEdit;
        protected global::System.Web.UI.WebControls.Panel pnlNoQuestions;
        protected global::System.Web.UI.WebControls.Panel pnlLocationModal;
        protected global::System.Web.UI.WebControls.TextBox txtModalDept;
        protected global::System.Web.UI.WebControls.TextBox txtModalSubDept;
        protected global::System.Web.UI.WebControls.TextBox txtModalLocationName;
        protected global::System.Web.UI.WebControls.Button btnCancelLocation;
        protected global::System.Web.UI.WebControls.Button btnSaveLocation;
    }
}
