//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymkhanaLibrary {
    
    public partial class Pages_EmpComplaintStatus {
        protected global::System.Web.UI.WebControls.Content Content1;
        protected global::System.Web.UI.WebControls.Content Content2;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divIdentityCard;
        protected global::System.Web.UI.WebControls.Panel pnlSessionEmployee;
        protected global::System.Web.UI.WebControls.Literal litEmployeeName;
        protected global::System.Web.UI.WebControls.Panel pnlDropdownEmployee;
        protected global::System.Web.UI.WebControls.DropDownList ddlSenderEmployee;
        protected global::System.Web.UI.WebControls.GridView gvComplaints;
        protected global::System.Web.UI.WebControls.LinkButton btnReminder;
    }
}
