//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymkhanaLibrary {
    
    public partial class Pages_EmpComplaintPanel {
        protected global::System.Web.UI.WebControls.Content Content1;
        protected global::System.Web.UI.WebControls.Content Content2;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.DropDownList ddlSenderDeptFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlTargetDeptFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        protected global::System.Web.UI.WebControls.TextBox txtFromDate;
        protected global::System.Web.UI.WebControls.TextBox txtToDate;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.GridView gvComplaints;
        protected global::System.Web.UI.WebControls.LinkButton lnkAction;
        protected global::System.Web.UI.WebControls.Panel pnlAction;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseModalX;
        protected global::System.Web.UI.WebControls.HiddenField hfEmpComplaintID;
        protected global::System.Web.UI.WebControls.Literal litCompSubject;
        protected global::System.Web.UI.WebControls.Literal litCompSender;
        protected global::System.Web.UI.WebControls.Literal litCompDetail;
        protected global::System.Web.UI.WebControls.DropDownList ddlUpdateStatus;
        protected global::System.Web.UI.WebControls.TextBox txtRemarks;
        protected global::System.Web.UI.WebControls.Button btnSaveStatus;
        protected global::System.Web.UI.WebControls.Button btnCancelAction;
    }
}
