//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymkhanaLibrary {
    
    public partial class Pages_FeedbackSubmit {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        protected global::System.Web.UI.WebControls.Literal litDeptName;
        protected global::System.Web.UI.WebControls.Literal litFeedbackTitle;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.Literal litInstructions;
        protected global::System.Web.UI.WebControls.TextBox txtMemberNo;
        protected global::System.Web.UI.WebControls.TextBox txtMemberName;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        protected global::System.Web.UI.WebControls.CheckBox chkIsComplaint;
        protected global::System.Web.UI.WebControls.Panel pnlRating;
        protected global::System.Web.UI.WebControls.Repeater repQuestions;
        protected global::System.Web.UI.WebControls.PlaceHolder phRating;
        protected global::System.Web.UI.WebControls.PlaceHolder phOptions;
        protected global::System.Web.UI.WebControls.Repeater repOptionItems;
        protected global::System.Web.UI.WebControls.Panel pnlSubject;
        protected global::System.Web.UI.WebControls.TextBox txtSubject;
        protected global::System.Web.UI.WebControls.Literal litCommentsLabel;
        protected global::System.Web.UI.WebControls.TextBox txtComments;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccessMessage;
    }
}
