//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefundFee {
    
    public partial class MemberSurvey {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.HiddenField hfShowPopup;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlWelcomeBanner;
        protected global::System.Web.UI.WebControls.Literal litSubDeptWelcome;
        protected global::System.Web.UI.WebControls.Panel pnlDirectAccess;
        protected global::System.Web.UI.WebControls.TextBox txtMemberNoDirect;
        protected global::System.Web.UI.WebControls.TextBox txtPhoneNumberDirect;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPhoneDirect;
        protected global::System.Web.UI.WebControls.TextBox txtRemarksDirect;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvRemarksDirect;
        protected global::System.Web.UI.WebControls.Repeater rptQuestionsInline;
        protected global::System.Web.UI.WebControls.HiddenField hfQuestionIdInline;
        protected global::System.Web.UI.WebControls.HiddenField hfQuestionTypeInline;
        protected global::System.Web.UI.WebControls.PlaceHolder phOptionsInline;
        protected global::System.Web.UI.WebControls.Button btnSubmitInline;
        protected global::System.Web.UI.WebControls.Panel pnlMemberPanel;
        protected global::System.Web.UI.WebControls.TextBox txtMemberNo;
        protected global::System.Web.UI.WebControls.Button btnFetchMember;
        protected global::System.Web.UI.WebControls.Panel pnlMemberInfo;
        protected global::System.Web.UI.WebControls.Label lblMemberName;
        protected global::System.Web.UI.WebControls.TextBox txtPhoneNumber;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPhone;
        protected global::System.Web.UI.WebControls.TextBox txtRemarks;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvRemarks;
        protected global::System.Web.UI.WebControls.Panel pnlDeptSelection;
        protected global::System.Web.UI.WebControls.Label lblDept;
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartment;
        protected global::System.Web.UI.WebControls.Label lblSubDept;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubDepartment;
        protected global::System.Web.UI.WebControls.Button btnOpenModal;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl complaintModal;
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;
        protected global::System.Web.UI.WebControls.HiddenField hfQuestionId;
        protected global::System.Web.UI.WebControls.HiddenField hfQuestionType;
        protected global::System.Web.UI.WebControls.PlaceHolder phOptions;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
