//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class SiteMaster {
    protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
    protected global::System.Web.UI.ScriptManager ScriptManagerMaster;
    protected global::System.Web.UI.UpdatePanel upSidebar;
    protected global::System.Web.UI.WebControls.Repeater rptModules;
    protected global::System.Web.UI.WebControls.Repeater rptPages;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl liLoadMore;
    protected global::System.Web.UI.WebControls.LinkButton btnLoadMore;
    protected global::System.Web.UI.WebControls.Label lblUser;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divEmpInfo;
    protected global::System.Web.UI.WebControls.Label lblEmpName;
    protected global::System.Web.UI.WebControls.Label lblDesignation;
    protected global::System.Web.UI.WebControls.Label lblDepartment;
    protected global::System.Web.UI.WebControls.Label lblSubDept;
    protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
}
