//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Membership {
    
    public partial class ApplicantWiseReport {
        
        protected global::System.Web.UI.WebControls.LinkButton btnExportExcel;
        protected global::System.Web.UI.WebControls.LinkButton btnPrintReport;
        protected global::System.Web.UI.WebControls.Literal litTotalApplicants;
        protected global::System.Web.UI.WebControls.Literal litTotalFormFee;
        protected global::System.Web.UI.WebControls.Literal litTotalMFee;
        protected global::System.Web.UI.WebControls.Literal litTotalPaid;
        protected global::System.Web.UI.WebControls.Literal litTotalBalance;
        protected global::System.Web.UI.WebControls.TextBox txtApplicantNo;
        protected global::System.Web.UI.WebControls.TextBox txtApplicantName;
        protected global::System.Web.UI.WebControls.TextBox txtCNIC;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.GridView gvReport;
    }
}
