using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Form_cell.Applicant_Form
{
    public partial class ManageCard : Page
    {
        private string strConn = (ConfigurationManager.ConnectionStrings["MemberShipConnection"] != null) ? ConfigurationManager.ConnectionStrings["MemberShipConnection"].ConnectionString : "";

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                // Initial load
            }
        }

        protected void btnSearch_Click(object sender, EventArgs e)
        {
            BindCards();
        }

        private void BindCards()
        {
            string cardNo = txtSearchCardNo.Text.Trim();
            string memberNo = txtSearchMemberNo.Text.Trim();

            if (string.IsNullOrEmpty(cardNo) && string.IsNullOrEmpty(memberNo))
            {
                ShowMessage("Please enter Card No or Member No to search.");
                return;
            }

            using (SqlConnection con = new SqlConnection(strConn))
            {
                SqlCommand cmd = new SqlCommand("usp_SearchRFIDCards", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.Add("@CardNo", SqlDbType.NVarChar, 50).Value = cardNo;
                cmd.Parameters.Add("@MemberNo", SqlDbType.NVarChar, 50).Value = memberNo;

                SqlDataAdapter da = new SqlDataAdapter(cmd);
                DataTable dt = new DataTable();
                da.Fill(dt);

                gvCards.DataSource = dt;
                gvCards.DataBind();
                resultsPanel.Visible = true;
            }
        }

        protected void gvCards_SelectedIndexChanged(object sender, EventArgs e)
        {
            int cardID = Convert.ToInt32(gvCards.SelectedDataKey.Value);
            ViewState["SelectedCardID"] = cardID;

            GridViewRow row = gvCards.SelectedRow;
            string cardNo = row.Cells[1].Text;
            string memberNo = row.Cells[2].Text;

            litSelectedCardInfo.Text = string.Format("<strong>Tag:</strong> {0} | <strong>Member:</strong> {1}", cardNo, memberNo);

            // Check if card is already blocked
            using (SqlConnection con = new SqlConnection(strConn))
            {
                SqlCommand cmd = new SqlCommand("usp_GetCardStatusByID", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.Add("@CID", SqlDbType.Int).Value = cardID;
                con.Open();
                string currentStatus = Convert.ToString(cmd.ExecuteScalar());

                if (currentStatus == "Block" || currentStatus == "Blocked")
                {
                    ShowMessage("This card is blocked and status cannot be changed. A new card should be generated by RFID Issuance page.");
                    pnlUpdateStatus.Visible = false;
                    return;
                }
            }

            pnlUpdateStatus.Visible = true;
        }

        protected void btnCancelUpdate_Click(object sender, EventArgs e)
        {
            pnlUpdateStatus.Visible = false;
        }

        protected void btnSaveStatus_Click(object sender, EventArgs e)
        {
            if (ViewState["SelectedCardID"] == null) return;

            int cardID = (int)ViewState["SelectedCardID"];
            string newStatus = ddlNewStatus.SelectedValue;
            string remarks = txtStatusRemarks.Text.Trim();
            string updatedBy = Session["Emp_Name"] != null ? Session["Emp_Name"].ToString() : "Admin";

            bool success = false;

            using (SqlConnection con = new SqlConnection(strConn))
            {
                using (SqlCommand cmd = new SqlCommand("usp_UpdateCardStatus", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add("@CardID", SqlDbType.Int).Value = cardID;
                    cmd.Parameters.Add("@NewStatus", SqlDbType.NVarChar, 50).Value = newStatus;
                    cmd.Parameters.Add("@Remarks", SqlDbType.NVarChar, -1).Value = string.IsNullOrEmpty(remarks) ? (object)DBNull.Value : remarks;
                    cmd.Parameters.Add("@UpdatedBy", SqlDbType.NVarChar, 100).Value = updatedBy;

                    try
                    {
                        con.Open();
                        cmd.ExecuteNonQuery();
                        success = true;
                    }
                    catch (Exception ex)
                    {
                        ShowMessage("Error updating card status: " + ex.Message);
                    }
                }
            }

            if (success)
            {
                pnlUpdateStatus.Visible = false;
                txtStatusRemarks.Text = "";
                ShowMessage("Card status updated successfully.");
                BindCards();
            }
        }

        private void ShowMessage(string msg)
        {
            string script = string.Format("alert('{0}');", msg.Replace("'", "\\'"));
            ScriptManager.RegisterStartupScript(this, GetType(), "msg", script, true);
        }
    }
}
