//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Masters_Site {
    
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    protected global::System.Web.UI.WebControls.ContentPlaceHolder cphHead;
    protected global::System.Web.UI.WebControls.ContentPlaceHolder cphBody;
    protected global::System.Web.UI.WebControls.Literal litAvatar;
    protected global::System.Web.UI.WebControls.Literal litStaffName;
    protected global::System.Web.UI.WebControls.Literal litStaffRole;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divEmpInfo;
    protected global::System.Web.UI.WebControls.Label lblEmpName;
    protected global::System.Web.UI.WebControls.Label lblDesignation;
    protected global::System.Web.UI.WebControls.Label lblDepartment;
    protected global::System.Web.UI.WebControls.Label lblSubDept;
    
    /// <summary>
    /// lnkChangePassword control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.LinkButton lnkChangePassword;
    
    /// <summary>
    /// upSidebar control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.UpdatePanel upSidebar;

    /// <summary>
    /// rptModules control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Repeater rptModules;

    /// <summary>
    /// liLoadMore control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl liLoadMore;

    /// <summary>
    /// btnLoadMore control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.LinkButton btnLoadMore;
}
