//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Membership.Reports {
    
    public partial class DateYearWiseReport {
        
        protected global::System.Web.UI.WebControls.LinkButton btnExportExcel;
        protected global::System.Web.UI.WebControls.LinkButton btnPrintReport;
        protected global::System.Web.UI.WebControls.Literal litTotalApplicants;
        protected global::System.Web.UI.WebControls.Literal litTotalFormFee;
        protected global::System.Web.UI.WebControls.Literal litTotalMFee;
        protected global::System.Web.UI.WebControls.Literal litTotalPaid;
        protected global::System.Web.UI.WebControls.Literal litTotalBalance;
        protected global::System.Web.UI.WebControls.TextBox txtFromDate;
        protected global::System.Web.UI.WebControls.TextBox txtToDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.GridView gvReport;
    }
}
