//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Masters_Site {
    protected global::System.Web.UI.WebControls.ContentPlaceHolder cphHead;
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    protected global::System.Web.UI.ScriptManager ScriptManager1;
    protected global::System.Web.UI.UpdatePanel upSidebar;
    protected global::System.Web.UI.WebControls.Repeater rptModules;
    protected global::System.Web.UI.WebControls.Repeater rptPages;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl liLoadMore;
    protected global::System.Web.UI.WebControls.LinkButton btnLoadMore;
    protected global::System.Web.UI.WebControls.Literal litAvatar;
    protected global::System.Web.UI.WebControls.Literal litStaffName;
    protected global::System.Web.UI.WebControls.Literal litStaffRole;
    protected global::System.Web.UI.WebControls.LinkButton lnkChangePassword;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divEmpInfo;
    protected global::System.Web.UI.WebControls.Label lblEmpName;
    protected global::System.Web.UI.WebControls.Label lblDesignation;
    protected global::System.Web.UI.WebControls.Label lblDepartment;
    protected global::System.Web.UI.WebControls.Label lblSubDept;
    protected global::System.Web.UI.WebControls.ContentPlaceHolder cphBody;
}
