//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuestRoomApp.GuestRoomM {

    public partial class PreviousBillView {

        protected System.Web.UI.WebControls.TextBox txtSearch;
        protected System.Web.UI.WebControls.Button btnSearch;
        protected System.Web.UI.WebControls.Button btnClear;
        protected System.Web.UI.WebControls.Panel pnlSummary;
        protected System.Web.UI.WebControls.Label lblTotalBills;
        protected System.Web.UI.WebControls.Label lblSettledCount;
        protected System.Web.UI.WebControls.Label lblUnsettledCount;
        protected System.Web.UI.WebControls.Label lblTotalGross;
        protected System.Web.UI.WebControls.GridView gvBills;
        protected System.Web.UI.WebControls.GridView gvServices;
        protected System.Web.UI.WebControls.Panel pnlServices;
        protected System.Web.UI.WebControls.Label lblMsg;
    }
}
